FROM apache/airflow:2.6.3-python3.10

# Instalar librerias necesarias para el pipeline y conexion MySQL
RUN pip install --no-cache-dir \
    pandas \
    scikit-learn \
    palmerpenguins \
    pymysql \
    sqlalchemy